### ISSUE TITLE
"Conflict" (HTTP 409) when downloading list(s)

### ISSUE THREAD

**Issue by thomasmerz** [sjhgvr/oisd#1]
Some lists serve only a HTTP error [409](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409).
>   [i] Target: https://dbl.oisd.nl/
  [✓] Status: Retrieval successful
  [i] Imported 795358 domains
  [i] List has been updated
…
>   [i] Target: https://dbl.oisd.nl/nsfw/
  [✗] Status: https://dbl.oisd.nl/nsfw/ (409)
  [✗] List download failed: using previously cached list

Because Pi-hole is only storing the latest log from "updateGravity" (updating lists) I can only confirm that on three different systems there has been problems with the NSFW list.

I found this by accident, because I was observing very high CPU load and CPU pressure on my smallest cloud server for my private VPN running a Pi-hole **since Mar, 16th starting at 1:55am** - is there something running on your side that prevents successfull downloading some(?) lists from dbl.oisd.nl? But also some minutes ago while I was writing this issue I observed an 409 for NSFW list with my Pi-hole…

**Comment by sjhgvr** [comment]
https://www.reddit.com/r/oisd_blocklist/comments/11s6dov/important_update_changes_to_blocklist_syntax/

**Comment by thomasmerz** [comment]
I understand that you only support ABP syntax only for NSFW blocklist. But even when using `nightly`Pi-hole version supporing ABP syntax:
```
…
Mar 21 12:04:17   [i] Target: https://dbl.oisd.nl/
  [✓] Status: No changes detected
Mar 21 12:04:26   [i] Imported 851695 domains
…
Mar 21 12:04:51   [i] Target: https://dbl.oisd.nl/nsfw/
  [✗] Status: https://dbl.oisd.nl/nsfw/ (409)
Mar 21 12:04:51   [✗] List download failed: using previously cached list
Mar 21 12:04:51   [i] List contained AdBlock Plus style domains
Mar 21 12:04:53   [i] Imported 328596 domains, ignoring 5 non-domain entries
Mar 21 12:04:53       Sample of non-domain entries:
Mar 21 12:04:53         - 2023-03-16t00:43:32+0000
Mar 21 12:04:53         - 202303160043
Mar 21 12:04:53         - frequency)
Mar 21 12:04:53         - nsfw
Mar 21 12:04:53         - plus]
```
Also when using `curl` or `wget` or with all my browser that I have in petto (Firefox, Chrome, Edge, Safari; on MacOS, Linux, iOS) there's still a 409 for the NSFW blocklist 😢

**Comment by sjhgvr** [comment]
> I understand that you only support ABP syntax only for NSFW blocklist. But even when using `nightly`Pi-hole version supporing ABP syntax:
> 
> ```
> …
> Mar 21 12:04:17   [i] Target: https://dbl.oisd.nl/
>   [✓] Status: No changes detected
> Mar 21 12:04:26   [i] Imported 851695 domains
> …
> Mar 21 12:04:51   [i] Target: https://dbl.oisd.nl/nsfw/
>   [✗] Status: https://dbl.oisd.nl/nsfw/ (409)
> Mar 21 12:04:51   [✗] List download failed: using previously cached list
> Mar 21 12:04:51   [i] List contained AdBlock Plus style domains
> Mar 21 12:04:53   [i] Imported 328596 domains, ignoring 5 non-domain entries
> Mar 21 12:04:53       Sample of non-domain entries:
> Mar 21 12:04:53         - 2023-03-16t00:43:32+0000
> Mar 21 12:04:53         - 202303160043
> Mar 21 12:04:53         - frequency)
> Mar 21 12:04:53         - nsfw
> Mar 21 12:04:53         - plus]
> ```
> 
> Also when using `curl` or `wget` or with all my browser that I have in petto (Firefox, Chrome, Edge, Safari; on MacOS, Linux, iOS) there's still a 409 for the NSFW blocklist 😢

https://nsfw.oisd.nl

dbl (domain block list) = domains syntax, which is no longer generated for the nsfw list.

I'd also recommend you change https://dbl.oisd.nl into https://big.oisd.nl (which serves you the big oisd list in ABP syntax instead)

**Comment by thomasmerz** [comment]
Oh, I had some 🍅 on my 👀 … sorry and many thanks for helping!
```
  [i] Target: https://nsfw.oisd.nl
  [✓] Status: Retrieval successful
  [i] List contained AdBlock Plus style domains
  [i] Imported 341009 domains

  [i] Target: https://big.oisd.nl/
  [✓] Status: Retrieval successful
  [i] List contained AdBlock Plus style domains
  [i] Imported 291106 domains
```
👍🏼

**Comment by RUdovichenko19** [comment]
Ti KRASAVELA BRATUXA, IA PREDSTAVLIYUI KAK UDOVICENKOROMA19@GMAIL.COM PRIJDEIT W DWIZHENIE.🤭😁🤗🫂®️🧲©️™️🫂®️®️®️®️
