### ISSUE TITLE
Cant access the Oisd site

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [sjhgvr/oisd#13]
![2vx9iMfXZh](https://github.com/user-attachments/assets/3dd9bf71-e5c2-4f1f-9e5a-0c7a03456db3)

**Comment by AyanokojiK1yotaka** [comment]
The OISD blocklists are not updating on my Pi-hole either. It shows that the lists are unaccessable.

**Comment by AyanokojiK1yotaka** [comment]
Okay, i can access the site now

**Comment by sjhgvr** [comment]
Email notification for this got burried, didnt notice. Glad it's fxed now.
