### ISSUE TITLE
Access Denied to the OISD site

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [sjhgvr/oisd#14]
![eBAQLWhfGy](https://github.com/user-attachments/assets/9a724264-5752-4a53-83cb-fbcea1d3a28b)

**Comment by sjhgvr** [comment]
Multiple requests to https://fonts.gstatic.com/s/opensans/..... (not sure exactly where they are coming from, maybe a browser plugin or something) are being disallowed by CSP and reported to the CSP report URL. That report page gets requested multiple times a second triggering mod_evasive module, resulting in 403. Multiple consecutive 4xx errors result in IP ban.

You're not the only one encountering this issue either (I see more IP's running into this issue).
Thanks for reporting.
Will fix this asap ;)

**Comment by sjhgvr** [comment]
Fixed. Thanks again :)
