### ISSUE TITLE
oisd NSFW mini

### ISSUE THREAD

**Issue by ghost** [sjhgvr/oisd#15]
The NSFW list is very good (haven't found any false positives).

The only problem is that it's huge, sitting at about 464.000 entries right now.

It would be awesome if you would consider a size-optimised version for browser/mobile/hosts blocking that only contains domains from oisd NSFW that have been found on Top 1M lists ([example](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#gamblingmini)).

Hoping either you or maybe @hagezi would be up for it.

**Comment by sjhgvr** [comment]
NSFW Big, and NSFW Small
Good idea ;)

Have to see when I will be working on that, since I just became father for the second time :)
So that probably won't be this week.

**Comment by hagezi** [comment]
Congratulations @sjhgvr, have a great time. 

If you want me to provide my merged toplist, let me know. I ran the NSFW through my build system and came up with 114000 domains for a ‘mini’ version.

**Comment by sjhgvr** [comment]
> Congratulations @sjhgvr, have a great time.

Thank you

> If you want me to provide my merged toplist, let me know. I ran the NSFW through my build system and came up with 114000 domains for a ‘mini’ version.

Thanks but no need.
I've already added a new list: oisd NSFW small, based off of the Tranco List. https://oisd.nl/setup
Also since I don't provide domains/hosts syntax's any more, the list is much smaller then 114K.

Thanks all. I think I can close this now.
