### ISSUE TITLE
OISD-hufilter

### ISSUE THREAD

**Issue by TIBCSI66** [sjhgvr/oisd#16]
Hi,

In one of these forums it was written that OISD includes the following filter:hufilter.
On NextDNS, I see that it hasn't been updated in 7 months (hufilter).
In the case of Adguard, the hufilter is constantly updated.
OISD includes the hufilter?

Regards

**Comment by sjhgvr** [comment]
They changed URL's
https://github.com/hufilter/hufilter/issues/461

Old URL's, eg https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-dns.txt are no longer working.

NextDNS must still be using an outdated URL I think.

Oisd used these 3:

https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-dns.txt (now 404)
https://filters.adtidy.org/extension/chromium/filters/203.txt (Adguard Cached list)
https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter.txt (now 404)

I've removed those and replaced them by: https://filters.hufilter.hu/hufilter-dns.txt
Which says: Last modified: 10 Sep 2024 16:25 UTC

So yes, oisd included, and still includes the hufilter (the domain-blocks at least, not the content-filters, as oisd is not a content-filter)
