### ISSUE TITLE
ABP Samsung Browser additional

### ISSUE THREAD

**Issue by TIBCSI66** [sjhgvr/oisd#17]
Hi,

I would like to insert the OISD (big) list here.
that's what I need:
https.//....oisd....txt
could you give me a link?

Regards,

**Comment by sjhgvr** [comment]
Installed Samsung Browser.
Where in the settings does it allow me to add blocklist URL's?

**Comment by TIBCSI66** [comment]
A Galaxy eszközömről küldve.

Stephan van Ruth ***@***.***> ezt írta (időpont: 2024. okt.
27., Vas 10:13):

**Comment by sjhgvr** [comment]
I think something went wrong there...

**Comment by TIBCSI66** [comment]
Hi,

could you give me a good link?

https://.....oisd....txt

Regards,

A Galaxy eszközömről küldve.

Stephan van Ruth ***@***.***> ezt írta (időpont: 2024. okt.
29., Ke 22:58):

**Comment by sjhgvr** [comment]
Try:
https://big.oisd.nl?txt
