### ISSUE TITLE
importet FP's in NSFW list

### ISSUE THREAD

**Issue by spirillen** [sjhgvr/oisd#2]
Hey Stephan

just a friendly note about your NSFW lists.

You happens to import | distribute more than ~7.500.000 unnecessary records most of which is related to `blogspot.!com` as all blogspot are redirected to `.com` fro any other `blogspot.TLD` then there are a hole lot of tumblr sub domain, which are taken down or redirects to subpath.

Next to all of these, I do find a lot of dead domains related to your imports.

You can see those already marked as wontfix here: https://0xacab.org/my-privacy-dns/matrix/-/issues/?sort=created_date&state=opened&in=DESCRIPTION&search=oisd.nl&or%5Blabel_name%5D%5B%5D=Wontfix&first_page_size=100# 

For those I haven't tested yet: https://0xacab.org/my-privacy-dns/matrix/-/issues/?sort=created_date&state=opened&in=DESCRIPTION&search=oisd.nl&first_page_size=20

To anticipate those that fails to be added... let's lists all of them our bot couldn't connect to: https://0xacab.org/my-privacy-dns/matrix/-/issues/?sort=created_date&state=opened&in=DESCRIPTION&search=oisd.nl&or%5Blabel_name%5D%5B%5D=On_Hold%3A%3AUnConfirmed&or%5Blabel_name%5D%5B%5D=Need%3A%3AScreenshot&first_page_size=20

while these 50 seems to make it to My Privacy DNS own lists: https://0xacab.org/my-privacy-dns/matrix/-/issues/?sort=created_date&state=opened&in=DESCRIPTION&search=oisd.nl&not%5Blabel_name%5D%5B%5D=Need%3A%3AScreenshot&not%5Blabel_name%5D%5B%5D=On_Hold%3A%3AUnConfirmed&first_page_size=20

**Comment by sjhgvr** [comment]
I'm not sure I get what you're saying.. There's not a single blogspot.com domain in my nsfw lists.

**Comment by spirillen** [comment]
@sjhgvr darm yeah your right, you link to them, you do not import and build... you right.

But then let me suggest you to walk through the list of linked source, to rule out the worst :smirk:

**Comment by sjhgvr** [comment]
Your first link shows me https://i.imgur.com/FM7QbT2.png

And I'm not sure what to do with those links, I do my own checks to see if a website is nsfw or not, I don't need no screenshots to verify and such.

If you know of any false positives in the oisd nsfw list, please report them [here](https://oisd.nl/report), or if you have new nsfw domains I'm not aware of; report them [here](https://oisd.nl/nsfw_reporter.php)

Thanks
