### ISSUE TITLE
Blocking TLDs run by the ICM registry instead of individual domains

### ISSUE THREAD

**Issue by mtheofy** [sjhgvr/oisd#21]
Hi,

I use the NSFW small RPZ list, so I don't know whether this idea applies to other formats.

The idea is to block the .xxx .adult .sex and .porn using entries such as 
```
*.xxx CNAME .
*.porn CNAME .
*.adult CNAME .
*.sex CNAME .
```
These TLDs are run by the [ICM Registry](https://icmregistry.biz/) (see also [here](https://en.wikipedia.org/wiki/.xxx))

This will lead to removing the individual site entries such as:

```
xxvideos.xxx CNAME .
*.xxvideos.xxx CNAME .
```
My count on the nsfw small rpz list (202412131411 version) gives the below:
574 entries for .xxx
174 entries for .porn
14 entries for .adult
106 entries for .sex

Might seam like a small optimization but it simplifies things and enforces the rational behind these domains.

Thanks for all your efforts

**Comment by sjhgvr** [comment]
Done. Thanks :)
Please let me know if it works for you.

**Comment by mtheofy** [comment]
Works great!
Thanks a lot
