### ISSUE TITLE
False negatives?

### ISSUE THREAD

**Issue by MrRobojack** [sjhgvr/oisd#22]
Hi Stephan,

Does **oisd** also handle 'false negatives' ? 

If so: where / how to report? 
If not: same question, more or less :)

So, for instance, if one would find a porn site bypassing the current NSFW list, could one report this here, or should one address all the authors of:   https://oisd.nl/includedlists/nsfw  or sth?

Thanks in advance!
Cheers
__

Direct motivation :

https://yandex.com  --> images   keyword porn  -- but ok, these are only images, but...
https://yandex.com  --> videos   keyword porn  -- the preview of the video seems to play regardless whether the website where the video is loaded is blocked (by NSFW) or not.

Example:

  https://yandex.com/video/preview/16070710503980732070?utm_campaign=morda&utm_medium=com

  Hosting website: http://ukdevilz.com/watch/-169878827_456239932 [ BLOCKED ]

  Video info says preview is hosted at:  cdn-pr.pvvstream.pro  however the actual vid seems to be on yandex-video.naydex.net in this case

  Actual preview:  See long link below.

Some sites that host content which isn't blocked:

yandex-video.naydex.net
cdn2.pvvstream.pro
hot2.embed-player.space

But, there's looots more it seems...

__

Long link: 

https://yandex-video.naydex.net/1kc51q169/18d4cfeLfn/0-EWb8ecgUBFfwCKqmEqNrGOIwBpdsfbQU1BansvjLUSUzvir_fUSzf1QSwV_5xadMrMdhIDmlIQPQwcbzjQ1_P_JkLgg5ooRk8FwrJOHwqz5Qo1TEvG-gZkWHtXJYWVE3gLz5bD5G0SxXFSDsKCd1-w4Gk8ELBaIis-Ok0898bh8RRi-pqOO0ZsMdW-cDYbp8EWP0N19Ms8c098bguXtyV1EduJ-8J1Kft2cCXAoH1sj_pjNiO7XjEZJCZnHPP8wNcOS96tkjlDbhbwlXsEF5fTKRVrVejBLWZPf18osI4vQjDhoMzabCvCYVEe2YV1eqH_SRAOkU8HPgkDXBjwzdTzCV3fkaoaf0AG84h6NhG2xwsCRUP77ztQcGVSArCyIXQo_bD-3kk7w35aHtWBb06T1WIwA65cERcnMUc71839yypt1LuvL29wPfWLegIRjsEdDXBt1tkUaFJtbiWhiBduMduOyMVsJ8ZaYCP-o05Ym-VDNzC9Xh8rBDV9Bvb92PAaQfKTtRx6bAfUlkQbILbAISRbScvRAnNOe3gdtL8YTjLpo-jQZzfjY0YR-75IW43lazIfmFYnHCocXC7V_fDWA3_ZuYoeU2oW_Z9BDzuE9h84eXvj2g1Gc35_CaqqIUsxwq3rw0Q6_2pmAvGXQ1Kix3UtH59qED4FNlc6wNPn2Ahex7CzBkxOFeO3UQUqv9ErL1l76OANa0pFdgGQjwl2Kt-IxNdnCv5xRjHHp2BorMpVEh27cAEpKyNzPO3c0_kPSPuclztldi3OrFIdFIjMKg1rWs3HD1hRRmMUl7IpQxDztcvFaDjZcUgT5YN1ZJPkVCwyp2s3NiUuZBvV-v3aJ0vXuqsGfVEF6J5nPBSw6gcLeVzFyB9DaEV3NaGXAWkSzYvp1HU64FpyFP2bX0id_HYKAq1uByceInw9_-rT8wdl3JeuOE9ZJvK0fR4rqes_JH5c1_o3emZIdByCgCdwPueuzdNdAsFPURLftXV_if5yDye1Zx8pBBhtHfP84PwLXdmXgwpudwb8vm8CEZrWAQBDTenvFmNxfmwairARaQ35rc33aRH5e247yLljSqfsRjwAs2csIy8kYjbT-MDRL0rjtpACYVce_ZByORKq8CEhcEDOwxtncl9oPrqiBGk1-oDN7FMW2k9wJMmBXF6E2WQTBaNuIjczDXsZ0PrUwBdC5YKXPkR9B9WJTxYwicYkCUl_5Oo8dEpAWyGBvDd3HcSu9_9qHN1WVDj0klNDgsxfOxKAfgEjMS1tOMHww9crS9K3lDhSWwfqlk4LMbTMCwVaYsraNFFteGI8mrILXRviosTvbxjKamMc2Zx9eaT-ZS0SmEo_CT47bAff68boLX7LnLg4WE4_yo9tGhur6jAHckPU7BZ8RHNcH5uWI3wW3YTj3W0-51twJdajR3-ny2sPArlMESgIE1sf29_F9QpNx6KQPU99DtaefgwFq88RIkRE--EKWVp8XSijixpzOcWT2-VvPsNwYTrfmmd9n_t_KAe6TA0PCT97Bc_x_9kbQ8SziD1HUyXXiGcYO5fyBAN4QPPgA0JzfkI-sJUlWDLui_3sUBj7fE490rBVWqL9ZSwFs3AYKToBeS3B18f6Glzds5cDRGsewYxtKDWR6jUpTWTJ-Bx4VW5uCLSsNEkM-JvP0HA991x1B9W4cVmP9VcLC5JaAR02DXk2_M_CyiVMwqebG0xCBvWbYDsCn8InD2BF-8UlXltheR-WliZDDs642PtqN8BjRSHysE55rt5gFw6mTic8DDx5Bvfq0-IFYcGxqTxHbx3MikElB7f2HD1KdfD-B3hmQ30Xpp0XchPcpdbzRjLycGEGw5lsaqfiXxsMmH8SBDMeZx_i-tHVKmX-s4QYRmAd04t6Byep7AYBb0rwyj92e0lbO5etJnII86vK72Qd-FdhDMO2fV6I_lccGaZxHx8QEHI6wvL16BNh-5-MCn5LAd26Qy0RjNcRC2BZ8dg3a1t4XCKcqyhSK_m359tQGudeTT_Dhk5_u-hJGDKHdzA6NjhDB_zu3fA7XduFkypySTjkpGAiNonyCwVmfMrQKmhGe3AEuq4MQznZld3-SSnnaHUM_4l3Q4fYThU8lWwXBCksYzXu3cTkIETBmacoT3474r1MPz-k9Tc5fmHs3wJARmNdI7C5FHMb3bLA8kcY_mphJN2URn66520SBptFDyQzG3M76-vh1gtK9JyDIF1cIOeuagEKi8YUFGlgw_s9UXJiaxuUoipcLdqNzeJpK_N8VT_9p2dboMhQEB6FTh0EEgZGNc_a3NowYOe3jgpeTAHNtkYrGKjNOgtiWc7rF0dfc3kAm7QHVRf6hvbPQz76U1s75YNjeIfMVBMYtk4hDCU-RTTw1vr9I0bpkrg_bH0ux5NiLSCw6hQNf2j7zS9VcFFPA7y8OGoz3ZTA72kK6WlLHty3QWSpw2IMBYd1BwA6IkU92tX-wi1sx76YI1FiENa3fD8rn9YCP3pD1Pwbf1hxbxmZsQ1WBu2y4uB_GsF8cjffsldKjMJPMyGVRx8vGRBkLs_f-vUnb9-CjgFFfB3tkV47Ip_KKwNrfeP8B2JcRkMIv7MpezLvq-_ddyb4QVck-ZlUWbPWQw4DrXgECTQXVDDy5uLmMGjFv6wLR10E7oZ-GASv2iseeVzm7wlHVnt3IZy1Am0T0rLo3nYU4FtoJv6GTEed3mA2E410Oy0_EGcx6tvf8TFExoSPOFlrHfSdTAQ6u8AZBmJr5NAXc3RpeyCaiThwMu-r6NZfAthIcRTRul1MnfxkIw-zeQU4GzxaHPv6-t0FbOKThyVscg3Pq2MtMJPzPx5YTsPhCGtWR34GlZ8JVxfFo8PvUh_df3Ug5qdiaL3gXw8FvHkROTA8eQH87PT0A2PZpackTXwfz4hAOjCs2QoiYWDE0RpYVW1UHbWdKW4f4JLa7HciwHBuFdaWdmmL_kI0CbtVIAkoGX071Nnz_hBj4YOoBUBDGcekbzYdtMwdJlJ75dMdeXpKax6ErjBDC_mk_eViPth2UCL0mW9ghcxiKQS5cSYUMB5bB9z4yNUkTcI/0x1c08506a220/pages-common/iframe-default/iframe-default.html#html=%3Ciframe%20src%3D%22https%3A%2F%2Fnmcorp.video%2Fplayer%2F-169878827_456239932%3Fm%3D88efa6ddc325a7def5bab1d8c8627d08%22%20frameborder%3D%220%22%20scrolling%3D%22no%22%20allowfullscreen%3D%221%22%20allow%3D%22autoplay%3B%20fullscreen%3B%20accelerometer%3B%20gyroscope%3B%20picture-in-picture%22%20aria-label%3D%22Video%22%3E%3C%2Fiframe%3E&autoplay=1&mute=1&hidden=externalPlayback&counters=%7B%22reqid%22%3A%221734335337668277-15068908089549244490-balancer-l7leveler-kubr-yp-vla-85-BAL%22%2C%22duration%22%3A899%2C%22live%22%3Afalse%2C%22videoUrl%22%3A%22http%3A%2F%2Fukdevilz.com%2Fwatch%2F-169878827_456239932%22%2C%22heartbeats%22%3A%7B%22singlePath%22%3A%22heartbeat.single.fserp%22%2C%22noRepeat%22%3Atrue%7D%2C%22table%22%3A%22video_tech%22%7D

**Comment by sjhgvr** [comment]
Report NSFW domains here:  https://oisd.nl/nsfw_reporter (Link found in various pages of https://oisd.nl/)

The purpose of the NSFW blocklist is to restrict access to NSFW content directly hosted on specific domains, not to block tools like search engines that have legitimate, widespread uses beyond NSFW material. Blocking search engines would disrupt normal, non-NSFW use cases for a vast majority of users. Additionally, many search engines offer safe search settings to filter NSFW results if configured properly. It’s up to users or network administrators to leverage these features rather than blanket-blocking search engines.
