### ISSUE TITLE
GoodbyeAds - Spotify

### ISSUE THREAD

**Issue by ghost** [sjhgvr/oisd#4]
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Spotify-AdBlock.txt

Hi there,

Would you please consider adding GoodbyeAds Spotify to your lists/hosts?

This can reduce Spotify ads and it does not break the app/website.

Thank you.

**Comment by sjhgvr** [comment]
https://oisd.nl/faq#addlist
https://oisd.nl/faq#listnotincluded
