### ISSUE TITLE
Steam Guard cannot login to Steam

### ISSUE THREAD

**Issue by FadeMind** [sjhgvr/oisd#6]
HI @sjhgvr 
Steam cannot log me in.
Used: ControlD Free DNS DoH with OISD Full list. 
Change to Google DNS resolve issue. 
Cannot check what is blocked here.

**Comment by sjhgvr** [comment]
Cannot reproduce.
Works here on my galaxy S23

**Comment by FadeMind** [comment]
Desktop Client have connection issue, not app mobile OR  website.

**Comment by FadeMind** [comment]
@sjhgvr nevermind. Internal server issue. Not related with OISD. Time - 
https://downdetector.pl/status/steam/

Thanks  for feedback anyway.
