### ISSUE TITLE
No update since 26th August 2023

### ISSUE THREAD

**Issue by tina-hello** [sjhgvr/oisd#8]
Is this repo deprecated, and should users update their filter URL to those listed in the main site?

**Comment by sjhgvr** [comment]
Whoops. Didn't notice the lists failed to push to github. Will fix.

**Comment by sjhgvr** [comment]
Fixed. I've also noticed oisd on NextDNS wasn't being updated. (They get [the list from github](https://github.com/nextdns/blocklists/blob/5d159f16f881206caf1e96cbf24ad919a4ffb93c/blocklists/oisd.json) as well)

Thanks 👍
