### ISSUE TITLE
filter list-incorrect blocking

### ISSUE THREAD

**Issue by TIBCSI66** [sjhgvr/oisd#9]
Hi,
I use NextDNS.
filters:OISD,Adguard,Hagezi Pro++
I want to watch a video on this page, but it is blocked by OISD.
Hagezi already fixed it, I asked for it.
https://www.mafab.hu
Please unblock the page!
Regards

**Comment by TIBCSI66** [comment]
Hi,
I still can't watch videos on this site!
Please unblock the page!
Regards

**Comment by sjhgvr** [comment]
I missed the first email pointing me to this issue. Thanks for the follow up.
Fixed. Thanks :)
